version: '3'
services:
  npx:
    image: node:20.11
    user: node
    command: bash -c "npm install --ignore-scripts && npm start"
    volumes:
      - .:/sources
    working_dir: /sources
    ports:
      - 4242:4242
